// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwbZ6t0beil5Wu930RACJL7AnwbULJ6-o',
    appId: '1:209586099180:web:3b9af6362a2e6a54ae66c9',
    messagingSenderId: '209586099180',
    projectId: 'eltelostfound',
    authDomain: 'eltelostfound.firebaseapp.com',
    storageBucket: 'eltelostfound.firebasestorage.app',
    measurementId: 'G-4C66SRY1VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5WDMQ6FAVXhfat5Kn6yi7s-VLrNB4qp0',
    appId: '1:209586099180:android:7c8c64c8158eb227ae66c9',
    messagingSenderId: '209586099180',
    projectId: 'eltelostfound',
    storageBucket: 'eltelostfound.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmNQbNCJnJimKOaIY5PR0kNtEEtmGozS8',
    appId: '1:209586099180:ios:7a4389add732b08aae66c9',
    messagingSenderId: '209586099180',
    projectId: 'eltelostfound',
    storageBucket: 'eltelostfound.firebasestorage.app',
    iosBundleId: 'com.example.elteLostFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmNQbNCJnJimKOaIY5PR0kNtEEtmGozS8',
    appId: '1:209586099180:ios:7a4389add732b08aae66c9',
    messagingSenderId: '209586099180',
    projectId: 'eltelostfound',
    storageBucket: 'eltelostfound.firebasestorage.app',
    iosBundleId: 'com.example.elteLostFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwbZ6t0beil5Wu930RACJL7AnwbULJ6-o',
    appId: '1:209586099180:web:ab2fa4f0e7731253ae66c9',
    messagingSenderId: '209586099180',
    projectId: 'eltelostfound',
    authDomain: 'eltelostfound.firebaseapp.com',
    storageBucket: 'eltelostfound.firebasestorage.app',
    measurementId: 'G-K3E48V1048',
  );
}
